### PR TITLE
correct network and disk panel label arrow sign

### PR DESCRIPTION
**Pull request by DragoonZ**

### CODE REVIEW

**Comment by pixunil** [comment]
Please see also #17. I decided that in panel mode, the arrows shouldn't be displayed as default.

Imagine following setting for disk: `Write: %write Read: %read`
With arrows, it's `Write: 100 KiB/s ▲`, a bit unnecessary in my eyes, because the word does explain what this value mean. The user should type in what he likes, and if arrows are wanted, they can be inserted in settings as `%write ▲ %read ▼`.

However, I haven't tested your solution, but I think you're confusing some methods:
You are not calling the method like in the menu, you are calling another, [panel-specific method](https://github.com/pixunil/cinnamon-applet-system-monitor/blob/master/modules/__init__.js#L838) which does some number magic, so the panel does not jump around #16. It does not uses the argument `dir`, so I believe that your solution won't work…

**Comment by DragoonZ** [comment]
but not, it always shows ▼ for %write, %read, %down and %up

the arrow is showing by default.

so i think it should use formatBytes method?

it is using formatRate now

**Comment by DragoonZ** [comment]
ok, i know what's going on here

i am not using the git version, i downloaded it from cinnamon's applet manager

**Comment by pixunil** [comment]
Yes, I have been a bit lazy the past months, I'll try to upload the new version soon

**Pull request closed without merging**
